- type: job
  id: VDVSquadLeader
  name: job-name-vdv-squadleader
  description: job-description-vdv-squadleader
  playTimeTracker: JobVDVSquadLeader
  requirements:
    # COMMENTED OUT: CharacterSpeciesRequirement not supported (species requirement system not implemented)
    # - !type:CharacterSpeciesRequirement
    #   species:
    #     - Human
    # COMMENTED OUT: FactionRequirement not supported (faction system not implemented)
    # - !type:FactionRequirement
    #   factionID: "PACT"
    - !type:TraitsRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 78
  startingGear: VDVSquadLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconPACTSquadleader"
  requireAdminNotify: false
  supervisors: job-supervisors-rugov
  canBeAntag: false
  # COMMENTED OUT: AddComponentSpecial requires at least one component, but all components are commented out
  # special:
  # - !type:AddComponentSpecial
  #   components:
  #     # COMMENTED OUT: ChatRank and HullrotFaction not supported
  #     # - type: ChatRank
  #     #   rank: BF-rank-private
  #     # - type: HullrotFaction
  #     #   faction: VDV
  #     # - type: LanguageAdder
  #     #   addSpoken:
  #     #     - Russian
  #     #   addUnderstood:
  #     #     - Russian
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTCommand
  - PACTMaintenance
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: VDVSquadLeaderGear
  equipment:
    id: VDVSquadLeaderPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMilitaryWebbingRUFilledAK12
    jumpsuit: ClothingUniformJumpsuitCamoRUEMR
    head: ClothingHeadHatHelmetRUEMR
    eyes: ClothingEyesGogglesGreen
    outerClothing: ClothingOuterArmorPlateCarrierBlack
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackRucksackBlack
    neck: ClothingNeckIFFtapeWhite
    suitstorage: WeaponRifleRUAK12
    pocket2: PouchGrenadesFilledVDVRifleman
  storage:
    back:
    - Tourniquet
    - Zipties
    - Welder
