- type: job
  id: USMCMedic
  name: job-name-usmc-medic
  description: job-description-usmc-medic
  playTimeTracker: JobUSMCMedic
  requirements:
    # COMMENTED OUT: CharacterSpeciesRequirement not supported (species requirement system not implemented)
    # - !type:CharacterSpeciesRequirement
    #   species:
    #     - Human
    # COMMENTED OUT: FactionRequirement not supported (faction system not implemented)
    # - !type:FactionRequirement
    #   factionID: "NATO"
    - !type:TraitsRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 75
  startingGear: USMCMedicGear
  alwaysUseSpawner: true
  icon: "JobIconNATOMedic"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  # COMMENTED OUT: AddComponentSpecial requires at least one component, but all components are commented out
  # special:
  # - !type:AddComponentSpecial
  #   components:
  #     # COMMENTED OUT: ChatRank and HullrotFaction not supported
  #     # - type: ChatRank
  #     #   rank: BF-rank-corporal
  #     # - type: HullrotFaction
  #     #   faction: USMC
  #     # - type: LanguageAdder
  #     #   addSpoken:
  #     #     - LowImperial
  #     #   addUnderstood:
  #     #     - LowImperial
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOMaintenance
  - NATOMedical
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: USMCMedicGear
  equipment:
    id: USMCMedicPDA
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMedicalEMTFilled # ClothingBeltMilitaryWebbingUSFilledMP5
    jumpsuit: ClothingUniformJumpsuitCamoUS
    head: ClothingHeadHatHelmetUS
    eyes: ClothingEyesHudMedicalBF
    outerClothing: ClothingOuterArmorPlateCarrierTan
    shoes: ClothingShoesBootsJackFilled
    gloves: ClothingHandsGlovesLatex
    back: ClothingBackpackRucksackTan
    suitstorage: WeaponSubmachinegunUSMP5
    pocket1: PouchMagsPistolLargeFilledMP5
    pocket2: SyringeCaseFilledBF14
  storage:
    back:
    - SupplyBoxMedicalFilled
    - DefibrillatorCompactBF
