- type: job
  id: USMCRifleman
  name: job-name-usmc-rifleman
  description: job-description-usmc-rifleman
  playTimeTracker: JobUSMCRifleman
  requirements:
    # COMMENTED OUT: CharacterSpeciesRequirement not supported (species requirement system not implemented)
    # - !type:CharacterSpeciesRequirement
    #   species:
    #     - Human
    # COMMENTED OUT: FactionRequirement not supported (faction system not implemented)
    # - !type:FactionRequirement
    #   factionID: "NATO"
    - !type:TraitsRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 77
  startingGear: USMCRiflemanGear
  alwaysUseSpawner: true
  icon: "JobIconNATORifleman"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  # COMMENTED OUT: AddComponentSpecial requires at least one component, but all components are commented out
  # special:
  # - !type:AddComponentSpecial
  #   components:
  #     # COMMENTED OUT: ChatRank and HullrotFaction not supported
  #     # - type: ChatRank
  #     #   rank: BF-rank-private
  #     # - type: HullrotFaction
  #     #   faction: USMC
  #     # - type: LanguageAdder
  #     #   addSpoken:
  #     #     - English
  #     #   addUnderstood:
  #     #     - English
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: USMCRiflemanGear
  equipment:
    id: USMCRiflemanPDA
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAG
    jumpsuit: ClothingUniformJumpsuitCamoUS
    head: ClothingHeadHatHelmetUS
    eyes: ClothingEyesGogglesTan
    outerClothing: ClothingOuterArmorPlateCarrierTan
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackRucksackTan
    suitstorage: WeaponRifleUSM16A4
    pocket2: PouchGrenadesFilledUSMCRifleman
  storage:
    back:
    - Tourniquet
    - Zipties
    - Welder
